# Generated by Django 6.0.7 on 2026-07-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="airplanetype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="airport",
            name="closest_big_city",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="airport",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="crew",
            name="first_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="crew",
            name="last_name",
            field=models.CharField(max_length=64),
        ),
    ]
