# Generated by Django 6.0.7 on 2026-07-22 15:16

import airport_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport_api", "0002_alter_airplane_name_alter_airplanetype_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport_api.models.movie_image_file
            ),
        ),
    ]
